added redirect uri option
kir-dev/passport-authsch pull request #4
Opened 2024-10-30 23:34 UTC by FearsomeRover

Im not sure, how to test this. But it seems like we will need it.

2024-10-31 17:22 UTC, Tschonti requested changes
can't hurt, though I think authSch works without this.
please bump the version number in package.json as well, I think npm won't publish without that

2024-10-31 19:17 UTC, FearsomeRover commented
Well it works as long, as we only have one redirect option. But if you give multiple options (separated on the web by a space) you need to explicitly choose from it in the request.

2024-11-01 11:17 UTC, Tschonti commented
> Well it works as long, as we only have one redirect option. But if you give multiple options (separated on the web by a space) you need to explicitly choose from it in the request.

looool never knew yu could do that

2024-11-01 11:17 UTC, Tschonti approved these changes

2024-11-07 17:46 UTC, merged